//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sbs_hw1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stats
    {
        public int Id { get; set; }
        public string result { get; set; }
        public int userSteps { get; set; }
        public string userSign { get; set; }
        public System.DateTime date { get; set; }
    }
}
